import { useState } from "react";
import { reviewFixtures, type ReviewFixture } from "./fixtures";
import { siteCopy } from "./content/site";
import {
  AppShell, DemoBar, Navigation, StatusBand, VerdictCard, PreliminaryCard,
  FindingRow, Timeline, ListingCard, ReportVersionChain, ReviewerQueue,
  DemoControls, SectionHeading, EvidenceChip
} from "./components";

type View = "home"|"samples"|"check"|"report"|"reviewer"|"methodology";
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n);
const nav=[{label:"How it works",href:"#home"},{label:"Sample reports",href:"#samples"},{label:"Methodology",href:"#methodology"},{label:"Reviewer demo",href:"#reviewer"}];
const stateMeta:Record<string,{tone:"good"|"fair"|"caution"|"avoid";title:string;status:string;detail:string}>={
 issued_consistent:{tone:"good",title:"Evidence is consistent",status:"complete",detail:"No blocking conflicts found in the supplied material."},
 issued_with_caveats:{tone:"caution",title:"Consistent with caveats",status:"complete",detail:"Resolve the listed conditions before moving forward."},
 not_assessable_refunded:{tone:"fair",title:"Not enough evidence",status:"needs_info",detail:"The simulated fee is marked for a full refund."},
 superseded_upgrade:{tone:"fair",title:"Replaced by a newer review",status:"complete",detail:"Open the current version before making a decision."},
 voided_listing_change:{tone:"avoid",title:"Listing changed",status:"needs_info",detail:"Material changes mean this report no longer maps to the offer."},
 revoked_fraud_signal:{tone:"avoid",title:"Earlier outcome withdrawn",status:"needs_info",detail:"A post-issue signal requires a fresh review."},
 revoked_reviewer_error:{tone:"avoid",title:"Reviewer correction issued",status:"needs_info",detail:"The earlier comparison contained an error."},
 extension_available:{tone:"caution",title:"Waiting on evidence",status:"in_review",detail:"One seven-day extension is available for this chain."},
 appeal_pending:{tone:"caution",title:"Appeal in progress",status:"in_review",detail:"A different fictional reviewer is reconsidering one conclusion."}
};
function Button({children,onClick,secondary=false}:{children:React.ReactNode;onClick?:()=>void;secondary?:boolean}){return <button className={secondary?"button button--secondary":"button"} type="button" onClick={onClick}>{children}</button>}
function App(){
 const [view,setView]=useState<View>("home");
 const [fixtureId,setFixtureId]=useState(reviewFixtures[0].id);
 const [menu,setMenu]=useState(false);
 const [step,setStep]=useState(0);
 const [checked,setChecked]=useState<string[]>([]);
 const fixture=reviewFixtures.find(x=>x.id===fixtureId)??reviewFixtures[0];
 const go=(next:View)=>{setView(next);setMenu(false);window.scrollTo({top:0,behavior:"smooth"})};
 const navigation=<Navigation current={view==="samples"?"Sample reports":view==="methodology"?"Methodology":view==="reviewer"?"Reviewer demo":"How it works"} items={nav} menuOpen={menu} onMenuToggle={()=>setMenu(!menu)} action={<Button onClick={()=>go("check")}>Check a listing</Button>}/>;
 return <AppShell demo={<DemoBar label="Public interactive demo" message="Every listing, person, document, event and price is fictional." action={<button className="text-button" onClick={()=>go("methodology")}>Read the limits →</button>}/>} navigation={navigation}>
   {view==="home"&&<Home go={go}/>}
   {view==="samples"&&<Samples select={(id)=>{setFixtureId(id);go("report")}}/>}
   {view==="check"&&<Check step={step} setStep={setStep} checked={checked} setChecked={setChecked} go={go} select={setFixtureId}/>}
   {view==="report"&&<Report fixture={fixture} select={setFixtureId} go={go}/>}
   {view==="reviewer"&&<Reviewer select={(id)=>{setFixtureId(id);go("report")}}/>}
   {view==="methodology"&&<Methodology/>}
 </AppShell>
}
function Home({go}:{go:(v:View)=>void}){return <div>
 <section className="hero-rich container">
  <div><span className="eyebrow">{siteCopy.brand.eyebrow}</span><h1>{siteCopy.hero.title}</h1><p className="lede">{siteCopy.hero.body}</p><div className="hero-actions"><Button onClick={()=>go("check")}>{siteCopy.hero.primaryCta}</Button><Button secondary onClick={()=>go("samples")}>{siteCopy.hero.secondaryCta}</Button></div><p className="fine-print">Illustrative fee: USD 49 · simulated 24-hour target · no card required</p></div>
  <div className="hero-report"><span className="report-kicker">SAMPLE REPORT · DD-DEMO-101</span><VerdictCard verdict="good" title="Evidence is consistent" summary="The supplied listing and document image agree on the compared specifications." confidence="Physical inspection still required"><div className="mini-actions"><EvidenceChip tone="positive">Specifications align</EvidenceChip><EvidenceChip tone="caution">Possession unknown</EvidenceChip></div></VerdictCard></div>
 </section>
 <section className="container section-pad"><SectionHeading eyebrow="A calm process" title="Three steps between urgency and a decision" description="Every conclusion stays tied to its source. Unknowns remain visible."/><div className="steps-grid">{siteCopy.workflow.map(([title,body],i)=><article className="step-card" key={title}><span>0{i+1}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
 <section className="dark-panel"><div className="container split"><div><span className="eyebrow">What this is not</span><h2>No magic green light.</h2></div><div><p>This demo does not identify a stone, inspect a setting, establish ownership, or replace an independent in-person inspection.</p><button className="text-button light" onClick={()=>go("methodology")}>See every rule and limitation →</button></div></div></section>
 <section className="container section-pad"><SectionHeading eyebrow="Explore the system" title="Every difficult lifecycle state is visible" description="Open an issued report, a listing-change void, a correction, an appeal, or an evidence request." action={<Button secondary onClick={()=>go("samples")}>Browse all nine</Button>}/><div className="sample-strip">{reviewFixtures.slice(0,3).map(x=><MiniFixture key={x.id} item={x} onClick={()=>{}}/>)}</div></section>
 </div>}
function MiniFixture({item,onClick}:{item:ReviewFixture;onClick:()=>void}){const m=stateMeta[item.state];return <button className="mini-fixture" onClick={onClick}><span className={"signal signal--"+m.tone}/><small>{item.id}</small><strong>{m.title}</strong><span>{item.title}</span></button>}
function Samples({select}:{select:(id:string)=>void}){return <section className="container section-pad"><SectionHeading eyebrow="Synthetic report library" title="Nine states. Nothing hidden." description="Each example is deep enough to show how outcomes, corrections and lifecycle events stay visible."/><div className="catalog-grid">{reviewFixtures.map(item=><ListingCard key={item.id} eyebrow={siteCopy.verdictLabels[item.state]} title={item.title} seller={item.seller} price={money(item.askingPrice)} specs={[{label:"Shape",value:item.shape},{label:"Case",value:item.id}]} action={<Button onClick={()=>select(item.id)}>Open report</Button>}/>)}</div></section>}
function Check({step,setStep,checked,setChecked,go,select}:{step:number;setStep:(n:number)=>void;checked:string[];setChecked:(x:string[])=>void;go:(v:View)=>void;select:(id:string)=>void}){const items=["Listing snapshot","Document image","Return terms","Payment method"];const toggle=(x:string)=>setChecked(checked.includes(x)?checked.filter(y=>y!==x):[...checked,x]);return <section className="container section-pad narrow"><SectionHeading eyebrow="60-second preliminary check" title="Start with what the seller claims" description="This browser-only exercise sends nothing anywhere. Avoid entering real personal information."/><div className="progress-line"><span style={{width:`${(step+1)*33.33}%`}}/></div>{step===0&&<div className="form-card"><h2>Choose a sample listing</h2><p>Use fictional data to see how the review behaves.</p><div className="sample-choices">{reviewFixtures.slice(0,4).map(x=><button key={x.id} onClick={()=>{select(x.id);setStep(1)}}><strong>{x.shape}</strong><span>{money(x.askingPrice)} · {x.seller}</span></button>)}</div></div>}{step===1&&<div className="form-card"><h2>What evidence is available?</h2><p>A final outcome never treats missing information as a pass.</p><div className="check-grid">{items.map(x=><label key={x}><input type="checkbox" checked={checked.includes(x)} onChange={()=>toggle(x)}/><span><strong>{x}</strong><small>{x==="Document image"?"Use the fictional sample supplied in this demo.":"Available for comparison"}</small></span></label>)}</div><div className="form-actions"><Button secondary onClick={()=>setStep(0)}>Back</Button><Button onClick={()=>setStep(2)}>Generate preliminary read</Button></div></div>}{step===2&&<PreliminaryCard title={checked.length>=3?"No immediate conflicts in what you selected":"Not enough to say"} description="This first read only reflects the fields you chose. It cannot tell you to buy." missing={items.filter(x=>!checked.includes(x))} action={<div className="form-actions"><Button secondary onClick={()=>setStep(1)}>Edit evidence</Button><Button onClick={()=>go("report")}>Start demo review · no charge</Button></div>}/>}</section>}
function Report({fixture,select,go}:{fixture:ReviewFixture;select:(id:string)=>void;go:(v:View)=>void}){const m=stateMeta[fixture.state];const versions=fixture.supersededBy?[{id:fixture.supersededBy,label:"Current replacement",date:"Latest",note:"New evidence reviewed"},{id:fixture.id,label:"Earlier version",date:"Earlier",note:"No longer current"}]:[{id:fixture.id,label:"Current report",date:"Current",note:siteCopy.verdictLabels[fixture.state]}];return <div>
 <StatusBand status={m.status} label={siteCopy.verdictLabels[fixture.state]} detail={m.detail} updatedAt={"Case "+fixture.id} steps={["Received","Compared","Reviewed","Issued"]}/>
 <section className="container report-layout section-pad"><div className="report-main"><p className="report-kicker">EVIDENCE REVIEW · {fixture.id}</p><VerdictCard verdict={m.tone} title={m.title} summary={fixture.summary} confidence="Physical inspection still required" price={money(fixture.askingPrice)}><div className="report-actions"><Button onClick={()=>window.print()}>Print inspection copy</Button><Button secondary onClick={()=>go("samples")}>All samples</Button></div></VerdictCard>
 <section className="report-section"><SectionHeading eyebrow="Compared material" title="What we found"/><div className="findings">{fixture.evidence.map((x,i)=><FindingRow key={i} label={x.topic} verdict={x.result==="supports"?"positive":x.result==="conflicts"?"negative":"caution"} headline={x.detail} detail={x.source} evidence={[{label:x.result,tone:x.result==="supports"?"positive":"caution"}]}/>)}</div></section>
 <section className="report-section caveat-panel"><SectionHeading eyebrow="Before you pay" title="Limits and next steps"/><div className="two-col"><div><h3>What remains unknown</h3><ul>{fixture.caveats.map(x=><li key={x}>{x}</li>)}</ul></div><div><h3>At the inspection</h3><ol>{fixture.nextSteps.map(x=><li key={x}>{x}</li>)}<li>Match the physical inscription to the document in person.</li><li>Use a reversible payment method and written return terms.</li></ol></div></div></section>
 <section className="report-section"><SectionHeading eyebrow="Lifecycle" title="Every material event stays visible"/><Timeline currentId={fixture.lifecycle.at(-1)?.event} items={fixture.lifecycle.map(x=>({id:x.event,title:x.event,time:new Date(x.at).toLocaleDateString(),description:x.note,complete:true}))}/></section></div>
 <aside className="report-aside"><div className="sticky"><div className="scope-card"><span className="eyebrow">Scope</span><h3>Listing evidence only</h3><p>No physical possession. No stone identification. No ownership check.</p></div><ReportVersionChain versions={versions} activeId={fixture.id} onSelect={(v:any)=>{const found=reviewFixtures.find(x=>x.id===v.id);if(found)select(found.id)}}/></div></aside></section>
 </div>}
function Reviewer({select}:{select:(id:string)=>void}){const rows=reviewFixtures.map((x,i)=>({id:x.id,title:x.title,seller:x.seller,risk:x.state.includes("revoked")||x.state.includes("voided")?"high":x.state.includes("caveat")||x.state.includes("appeal")?"medium":"low",age:`${i+1}h`,stage:siteCopy.verdictLabels[x.state],assignee:i%3===0?"Fictional reviewer":"Unassigned"}));return <section className="container section-pad"><DemoControls scenario="standard" scenarios={[{value:"standard",label:"Standard queue"},{value:"overdue",label:"24-hour target missed"}]} onReset={()=>{}}/><ReviewerQueue title="Fictional reviewer workspace" rows={rows} metrics={[{label:"Open cases",value:"9",note:"synthetic"},{label:"Awaiting evidence",value:"2"},{label:"Needs second look",value:"1"}]} onOpen={(row:{id:string})=>select(row.id)}/><p className="reviewer-note">Role controls in this demo are presentation only. They are not access controls.</p></section>}
function Methodology(){return <section className="container section-pad policy"><SectionHeading eyebrow="Published methodology" title="The rules are more important than the ribbon" description="This demo uses a deterministic comparison. It cannot identify a physical stone."/><div className="policy-grid"><article><span>01</span><h2>Compare claims</h2><p>Listing details are compared with supplied fictional documents. Each finding names its source.</p></article><article><span>02</span><h2>Keep unknowns visible</h2><p>Missing critical evidence produces an evidence request or a not-assessable outcome—never a quiet pass.</p></article><article><span>03</span><h2>Require inspection</h2><p>Every outcome ends with an in-person checklist before payment.</p></article></div><div className="legal-block"><h2>Product limits</h2><p>This public demo uses synthetic data and local browser state. It is not an appraisal, valuation, authentication, insurance opinion, or purchasing advice. It does not handle payments, upload files, identify people, connect to laboratories, or store data on a server.</p><h3>Independence</h3><p>No commissions or referral fees from sellers, marketplaces, laboratories, insurers, lenders, or jewelers are represented in this demo.</p><h3>Lifecycle policy</h3><ul><li>Simulated target: 24 hours.</li><li>Not assessable after requested evidence: simulated full refund.</li><li>One appeal and one seven-day extension per report chain.</li><li>Material listing changes void the current report.</li><li>New evidence, reviewer error, fraud signal, or buyer request can withdraw an outcome.</li></ul></div></section>}
export default App;
